apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amazon.fullname" . }}
  labels:
    {{- include "amazon.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "amazon.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "amazon.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: amazon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10